### ISSUE TITLE
Throws exception on empty format string

### ISSUE THREAD

**Issue by tatsujin1** [alexei/sprintf.js#118]
`sprintf("", "abc");`
`[sprintf] unexpected placeholder`

I fixed it (I think) by changing the condition in `sprintf.parse()`:

`while(_fmt)`
to:
`while(_fmt.length > 0)`

Which is a bit illogical since the empty string is indeed a falsy value...

Browser: Chrome 54

**Comment by tatsujin1** [comment]
My bad, I had incorrectly wrapped it to be called using `"string".format()` ...

**Comment by alexei** [comment]
I'm not sure I understand

**Comment by tatsujin1** [comment]
Me neither, actually...

My initial description was misleading, I actually called sprintf using a wrapper that extended the String prototype. The above example actually looked like:

`"".format("abc")`

The wrapper I was using looks like this (I've now removed it and is calling `sprintf()` without it):
```
if(! String.prototype.format)
{
	String.prototype.format = function() {
		return sprintf.apply(null, [this].concat([].slice.call(arguments)));
	};
}
```

And for some reason, when using the wrapper sprintf() threw the above SyntaxError when the format string was empty.
