### ISSUE TITLE
No parameters rendered with "%s"

### ISSUE THREAD

**Issue by ImmortalJoker** [alexei/sprintf.js#123]
Hi,

could you please look at **get_type** function, it seems work not properly.

On your **format** function you're waiting for **"array"** type but you've got an **"array iterator"**.

That's why code will never be executed and you'll never see your parameters on the output string

**Comment by blackakula** [comment]
My suggestion is to use [Array.isArray()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) function for ES6. It's more reliable than the custom `get_type`

**Comment by litmit** [comment]
`get_type() === 'array'` is used only for testing the internal parsing structure, not parameters. 
(It test that RegExp.exec() return an array)

Can you give steps to reproduce an erroneous behavior?

**Comment by alexei** [comment]
I agree with @litmit - do provide an example

**Comment by alexei** [comment]
I think this was fixed
