### ISSUE TITLE
unexpected placeholder with use of %t

### ISSUE THREAD

**Issue by robsnell72** [alexei/sprintf.js#125]
sprintf("%t</BR>", isHappy(i)) results in unexpected placeholder

**Comment by alexei** [comment]
Well, that's so sad. What version are you using?

**Comment by robsnell72** [comment]
"sprintf-js": "^1.0.3"

**Comment by alexei** [comment]
Ah, sorry! Indeed, that feature's on master only

**Comment by alexei** [comment]
Published a new version. Should work from now on
