### ISSUE TITLE
Crash after minify js code

### ISSUE THREAD

**Issue by gribkovartem** [alexei/sprintf.js#159]
I've getting an error after my budle has been created. I think there is a problem in the end of angular-sprintf.js because of missing semicolon.

![screenshot_84](https://user-images.githubusercontent.com/1208750/34414647-85bd849e-ebfb-11e7-82da-a86f7e26b00b.png)
![screenshot_85](https://user-images.githubusercontent.com/1208750/34414648-85d9df54-ebfb-11e7-8cd1-3713239454e1.png)

**Comment by IMM0rtalis** [comment]
Just faced the same problem. Is this repo still maintained @alexei  ?

**Comment by alexei** [comment]
More or less. I don't intend to add any new features, but I'll take a look in the coming days at some of the bugs and see what I can do.

**Comment by IMM0rtalis** [comment]
Thx for the fast answer. If you want to share responsibilities for this project I bet you will find a few people to help you with. but pls choose carefully. Not that we have another overtake of a commonly used package :/

**Comment by alexei** [comment]
Fixed
