### ISSUE TITLE
Cannof find moduule sprintf

### ISSUE THREAD

**Issue by crazypigs** [alexei/sprintf.js#162]
Hi I cannot seem to get sprintf to work inside my ionic application. 

does it need to be added to the app module or something . 

I am currently just importing it like so and using it:
`import { sprintf } from 'sprintf';`
`sprintf("%s%s/communityMembers.json?auth=%s",
        GlobalVar.COMMUNITYAREAURL,
        areaName,token)`

**Comment by crazypigs** [comment]
I think i needed to import 
`import {sprintf} from "sprintf-js";
`
Notice i did **sprintf-js** and not **sprintf**
that seemed to do the trick 👍

**Comment by alexei** [comment]
Sorry about that!
