### ISSUE TITLE
vsprintf('%f', 0) --> Uncaught TypeError: [sprintf] expecting number but found undefined

### ISSUE THREAD

**Issue by claydodo** [alexei/sprintf.js#163]
It seems that vsprintf does not handle number 0 correctly: `vsprintf('%f', 0)` would yield this error:

> Uncaught TypeError: [sprintf] expecting number but found undefined

**Comment by alexei** [comment]
I'm sorry you are experiencing this issue. I just checked on my machine and it seems both `sprintf('%f', 0)` and `vsprintf('%f', [0])` return the right result. Have you tried turning your computer off and on again?
