### ISSUE TITLE
Crashes when faces the percentage with the following symbol that doesn't match anything

### ISSUE THREAD

**Issue by UprightBeats** [alexei/sprintf.js#169]
For example I want to process this string:
`<div id="data-app-%s-element" ng-controller="itemsData"><div ng-show="dataLoading" style="width: 100%; height: 30px; text-align: center;">'`
It crashes on the second percentage "%;"

**Comment by alexei** [comment]
If you want to output the `%` character, you need to escape it like so: `%%`

**Comment by UprightBeats** [comment]
You mean I should replace "100%;" with "100%%;"? But how in this case the style would work? Or the sprintf will change it back to just "%"?
