### ISSUE TITLE
Reduce the size of the npm package by limiting the included files

### ISSUE THREAD

**Issue by paazmaya** [alexei/sprintf.js#173]
Looks like the `files` property (https://docs.npmjs.com/files/package.json#files) is not used in `package.json` to specify the included files, nor is the `.npmignore` file (https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) is being used for blacklisting unwanted files, for the package published to npm.

Would you consider adding either the `files` property or the `.npmignore` file, so that the resulting package file would have smaller size?

The current size can be seen when executing the command `npm pack` (https://docs.npmjs.com/cli/pack).

> This issue was create via [tawata](https://github.com/paazmaya/tawata/)

**Comment by alexei** [comment]
Fixed
