### ISSUE TITLE
Remove browser .repeat polyfill requirement

### ISSUE THREAD

**Issue by ashwalk33r** [alexei/sprintf.js#192]
Reopens https://github.com/alexei/sprintf.js/issues/182

Why to user should worry about polyfills if it's literally used once?

https://github.com/alexei/sprintf.js/blob/36b04b33975e597b03737c3ed0a2a49ec1b2e8c4/README.md#L131

https://github.com/alexei/sprintf.js/blob/818a723f5b50c148b34cc310e76ff0ee22151497/src/sprintf.js#L134

**Comment by ashwalk33r** [comment]
@alexei Dare to answer the question?

**Comment by alexei** [comment]
I've already answered it, please look it up
