### ISSUE TITLE
unexpected placeholder when using object literal syntax

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [alexei/sprintf.js#194]
The below gives me unexpected placeholder:

```
    const user = {
          name: 'Dolly'
      }
      sprintf('<u>Welcome back %(name)!</u><br>See if you qualify below!', user);
```

However, this does not give an error:

```
      sprintf('<u>Welcome back %s!</u><br>See if you qualify below!','Dolly');
```

Why does object literal syntax give an error?

**Comment by alexei** [comment]
Try `sprintf('<u>Welcome back %(name)s!</u><br>See if you qualify below!', user)`

**Comment by laurent22** [comment]
Both doc and error message are inadequate here.
