### ISSUE TITLE
provide padding examples

### ISSUE THREAD

**Issue by enuggetry** [alexei/sprintf.js#202]
it would be great if you provided some padding examples with output results, as it's not entirely clear how it works.

**Comment by alexei** [comment]
Yeah, the readme assumes the user is familiar with the basics of `(s)printf`, perhaps wrongly. In the meantime, you can take a look over the [examples](https://github.com/alexei/sprintf.js/blob/master/test/test.js#L86-L100) in the test case. See also [PHP's sprintf docs](https://www.php.net/manual/en/function.sprintf.php), as this library initially followed PHP's spec which is slightly different than that of C/C++.
