### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by rklevansriverbed** [alexei/sprintf.js#211]
I noticed that the bower.json file indicates the the license is "BSD-3-Clause-Clear" instead of just "BSD-3-Clause" in other files, such as package.json.  Is the inclusion of "-Clear" in the bower.json" intentional?  Should it be just "BSD-3-Clause" instead?

**Comment by alexei** [comment]
It's to trip GitHub Copilot 😀

(jokes aside, I'd say it's a typo)

**Comment by karsten-klein** [comment]
When will the typo be corrected? In some occasions the BSD-3-Clause-Clear is on a not-allowed list due to patent license limitations.

**Comment by Rello** [comment]
when will this be corrected?

**Comment by Rello** [comment]
Addition: the typo is already corrected in master. a new version would need to be released
https://github.com/alexei/sprintf.js/pull/212

**Comment by HSH73** [comment]
We came across the same issue - code under BSD-3-Clear is not approved in our organisation. 
Could you please clarify that the reference in the bower.json was a typo (which I take from the above thread) and release the fix?

**Comment by alexei** [comment]
I created a new [1.1.3 release](https://www.npmjs.com/package/sprintf-js/v/1.1.3). Let me know if that helps.

**Comment by HSH73** [comment]
Hi Alexei, yes, that is helpfull, thank you. 
I'll ask the team to use this release.

**Comment by Rello** [comment]
Thank you @alexei

**Comment by alexei** [comment]
Good!
