### ISSUE TITLE
hx specifier doesn't work

### ISSUE THREAD

**Issue by kurdbohu** [alexei/sprintf.js#218]
%hx specifier is for short hexadecimal numbers (typically 2 bytes). For example:
`sprintf("%hX\n", 65536);   // = hexa 0`
`sprintf("%X\n", 65536);     // = hexa 10000`

The javascript version of sprintf throws error:
SyntaxError: [sprintf] unexpected placeholder

**Comment by alexei** [comment]
What's a "short hexadecimal number" in JavaScript?

**Comment by kurdbohu** [comment]
I mean, a short integer (typically 2 bytes) represented in hexadecimal form (largest number = 0xFFFF).

**Comment by alexei** [comment]
JS has `int`s and that's it
