### ISSUE TITLE
Add %g in the formater

### ISSUE THREAD

**Issue by lpatiny** [alexei/sprintf.js#54]
Be able for format a number based on significative digits would be nice. This is as far as I know the "%g" option
Trying in a batch 
* printf '%.4g' 123.12  --> 123.1
* printf '%.4g' 123123.12123 --> 1.231e-05
* printf '%.4g' 1223.12123 --> 1223
The equivalent in javascript would be "toPrecision"
* (123.12).toPrecision(4)
* (123123.12123).toPrecision(4)
* (1223.12123).toPrecision(4)
And yields the same result

**Comment by LasCondes** [comment]
This would help me too.

**Comment by LasCondes** [comment]
I've tried adding the following to get the behavior of %g. I wasn't able to use the %g tag so instead passing %b. This definitely is not a good way of doing this but at least getting the functionality of the %g.

````C++
function sprintf() {
    var key = arguments[0], cache = sprintf.cache
    if (!(cache[key] && cache.hasOwnProperty(key))) {
        cache[key] = sprintf.parse(key)
    }
    if(key.match(/b/)){   // This really should be g !!!
        key=key.replace("b","f");
        if (!(cache[key] && cache.hasOwnProperty(key))) {
            cache[key] = sprintf.parse(key)
        }
        f_test=sprintf.format.call(null, cache[key], arguments)
        key2=key.replace("f","e");
        if (!(cache[key2] && cache.hasOwnProperty(key2))) {
            cache[key2] = sprintf.parse(key2)
        }
        e_test=sprintf.format.call(null, cache[key2], arguments)
        if(e_test.length<f_test.length){
            key=key2
        }
    }
    return sprintf.format.call(null, cache[key], arguments)
}
````
