### ISSUE TITLE
Documentation for consoles

### ISSUE THREAD

**Issue by morenoh149** [alexei/sprintf.js#55]
I spent a long time fighting against this module because I was expecting `sprintf('%i', i)` to print directly to the console. In fact you must wrap this in a console.log like so `console.log(sprintf('%i', i))`.

This should be added to the readme. Related https://stackoverflow.com/questions/19837697/node-js-formatted-console-output

**Comment by ArmorDarks** [comment]
Hm, I can't understand, why `sprintf('%i', i)` had to print directly to console without `console.log()`? `sprintf` returns just simple string. Strings doesn't end up in console log magically by their own will.

**Comment by accidentallyc** [comment]
I second @ArmorDarks . Even in php and C `sprintf` (note the s) always returns and not prints xD maybe OP got confused cause it had the word print in it xD
