### ISSUE TITLE
SyntaxError unexpected placeholder if fmt ends with placeholder

### ISSUE THREAD

**Issue by blindlf** [alexei/sprintf.js#58]
```sprintf('%(name)', {'name': 'abc'})``` throws exception.
```sprintf('%(name)s', {'name': 'abc'})``` returns 'abc', and expects 'abcs'.

**Comment by blindlf** [comment]
Sorry, my mistake.

**Comment by andineck** [comment]
just ran into the same mistake. thx for posting. for others that are mistaken as well:

 - %s is a `String` Placeholder
 - %(name)s is therefore a `String` Placeholder with a variable name
 - %(anything) without following `type specifier` is an invalid placeholder -> throws `SyntaxError`
