### ISSUE TITLE
Negative number passed to the first '%f'.

### ISSUE THREAD

**Issue by hnilickam** [alexei/sprintf.js#80]
Hi, isn't this strange?
sprintf("%f and %f", 12, 34) returns '12 and 34' ...OK
sprintf("%f and %f", 12, -34) returns '12 and -34' ...OK
sprintf("%f and %f", -12, 34) returns '-12 and -34' ...???
sprintf("%f and %f", -12, -34) returns '-12 and -34' ...OK

**Comment by alexei** [comment]
Hey,

I created a test and am unable to confirm this behaviour.

Can you please give me some more information? Like version number, environment (i.e. browser or Node) etc.

Alex

**Comment by hnilickam** [comment]
Hi and thanks for your reply. 
I have played with it again, code is now simply your basic test, just a bit modified:


![sprintf](http://81.95.107.104/Autoplan/download/temp/sprintf.png) 

Sprintf.js and angular-sprintf.js are current ones.
Chrome is OK but FF42 and IE11 fail:
>I've got 4 apples and 2 oranges.
>I've got -4 apples and -2 oranges.
>I've got 4 apples and -2 oranges.
>I've got -4 apples and -2 oranges.

**Comment by alexei** [comment]
I checked with Safari (9.0.2), Chrome (47.0.2526.106) and Firefox (43.0.3) and could not reproduce this behaviour.
